### ISSUE TITLE
TFLite VX Delegate fails to build with TIM-VX 1.1.42

### ISSUE THREAD

**Issue by robert-kalmar** [VeriSilicon/tflite-vx-delegate#77]
The TIM-VX added the alpha parameter for Elu operator in this commit 
```
commit d0af7ae8df830c98323690ae5806d6af53dbb2c1
Author: chxin66 <57057788+chxin66@users.noreply.github.com>
Date:   Mon Apr 11 19:04:30 2022 +0800

    Support alpha in elu (#354)
    
    https://github.com/VeriSilicon/TIM-VX/issues/305    
    
     Signed-off-by: Chen Xin <jack.chen@verisilicon.com>

```
This change is not reflected in TFLite VX Delegate, and the build fails as follows: 
```
/media/edata/sdk/8mp-LF5.15-next_20220426/sysroots/armv8a-poky-linux/usr/include/c++/11.2.0/ext/new_allocator.h:162:11: error: no matching function for call to ‘tim::vx::ops::Elu::Elu(tim::vx::Graph*)’
  162 |         { ::new((void *)__p) _Up(std::forward<_Args>(__args)...); }
      |           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /home/nxf39574/2019_AITEC/REPOS/tim-vx/build/install/include/tim/vx/ops.h:27,
                 from /home/nxf39574/2019_AITEC/REPOS/tflite-vx-delegate/op_map.cc:41:
/home/nxf39574/2019_AITEC/REPOS/tim-vx/build/install/include/tim/vx/ops/activations.h:93:3: note: candidate: ‘tim::vx::ops::Elu::Elu(tim::vx::Graph*, float)’
   93 |   Elu(Graph* graph, float alpha);
      |   ^~~
/home/nxf39574/2019_AITEC/REPOS/tim-vx/build/install/include/tim/vx/ops/activations.h:93:3: note:   candidate expects 2 arguments, 1 provided
```

**Comment by sunshinemyson** [comment]
@robert-kalmar ,

Did you tried latest vx-delegate and tim-vx ? I think compile can pass.

**Comment by robert-kalmar** [comment]
@sunshinemyson , 
with latest TIM-VX and VX Delegate the build pass. The build issue is fixed. Build configuration:
TIM-VX - rev. f8741b4704ab9caffd49f6fc15f72616962ba1d1
VX Delegate - rev. 995af2dbaf38960f29f0224f90126758e2016dbb
